[package]
name = "advent_of_code_2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# debug_fn = "0.3"
# num-bigint = "0.4"
petgraph = "0.6.2"
petgraph-evcxr = "*"